{"name": "Тест заранее проваленный", "status": "skipped", "statusDetails": {"message": "XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be", "trace": "E   AssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be"}, "description": "Открываем страницу товара \n    Добавляем товар в корзину \n    Проверяем, что нет сообщения об успехе с помощью is_not_element_present", "attachments": [{"name": "stdout", "source": "a8933648-9c74-453b-aff8-9bba3a56a4af-attachment.txt", "type": "text/plain"}], "start": 1745139482341, "stop": 1745139490492, "uuid": "8508802c-96f4-4d63-b5eb-6304debedc97", "historyId": "3d9d103aac06685104a4d4a2482f03d0", "testCaseId": "3d9d103aac06685104a4d4a2482f03d0", "fullName": "tests.ui.test_product_page#test_guest_cant_see_success_message_after_adding_product_to_basket", "labels": [{"name": "feature", "value": "Basket"}, {"name": "story", "value": "Basket Feature"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Now not work!')"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_product_page"}, {"name": "host", "value": "c045dde3dc68"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_product_page"}]}