{"name": "Тест заранее проваленный", "status": "skipped", "statusDetails": {"message": "XFAIL Now not work!\n\nAssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be", "trace": "E   AssertionError: Success message(NAME_ITEM_IN_MESSAGE) is presented, but should not be"}, "description": "Открываем страницу товара \n    Добавляем товар в корзину \n    Проверяем, что нет сообщения об успехе с помощью is_not_element_present", "attachments": [{"name": "stdout", "source": "bc5127a2-3674-40e6-a243-660f9f6d86c2-attachment.txt", "type": "text/plain"}], "start": 1745140180964, "stop": 1745140188561, "uuid": "130778ab-a63a-4ef9-804f-f536215fe50d", "historyId": "3d9d103aac06685104a4d4a2482f03d0", "testCaseId": "3d9d103aac06685104a4d4a2482f03d0", "fullName": "tests.ui.test_product_page#test_guest_cant_see_success_message_after_adding_product_to_basket", "labels": [{"name": "story", "value": "Basket Feature"}, {"name": "feature", "value": "Basket"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Now not work!')"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_product_page"}, {"name": "host", "value": "b171024d8e94"}, {"name": "thread", "value": "6-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_product_page"}]}